apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic-app
  labels:
    app: spring-petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      containers:
        - name: spring-petclinic-app
          image: sandalichandrasekara/petclinic-app:latest 
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/petclinic"
            - name: SPRING_DATASOURCE_USERNAME
              value: "petclinic"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "petclinic"
          ports:
            - containerPort: 8080