apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.appPort }}
      targetPort: {{ .Values.appPort }}
  selector:
    app: {{ .Values.appName }}
