name: snyk security

on:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:

  scan:
    name: snyk-scan
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Run Snyk Security Scan
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          npx snyk auth $SNYK_TOKEN
          npx snyk test

