name: Trivy

on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  scan:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Run Trivy Scan - Filesystem
        run: |
          trivy fs --severity HIGH,CRITICAL,MEDIUM,LOW .
      
      - name: Run Trivy Scan - Configuration
        run: |
          trivy config --severity HIGH,CRITICAL,MEDIUM,LOW .

      - name: Comment on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: scan-results.md
